import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "@/app/globals.css";

import HeaderLayout from "@/components/header/headerLayout";

const PixelFont = Lora({
    variable: "--font-pixel",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Raifi.archive",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en" className={`${PixelFont.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col max-w-5xl mx-auto">
                <HeaderLayout/>
                {children}
            </body>
        </html>
    );
}
